name = "toctoc"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ConversationDO"

[[durable_objects.bindings]]
name = "USERS"
class_name = "UserDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ConversationDO", "UserDO"]
